### PR TITLE
Documentation image files for spot light

### PR DESCRIPTION
**Pull request by mehrab2603**
This commit adds documentation image files for spot light.

### CODE REVIEW

**Comment by Speierers** [comment]
Could we use the `matpreview` floor here, maybe keep the envmap and add a strong spot light? This would be more illustrative 😉

**Comment by mehrab2603** [comment]
Updated the images. Please let me know if they are okay.

**Comment by Speierers** [comment]
I am sorry to be picky about this @mehrab2603, but I think it would be better to have the spot light above, pointing downward. On your images it is hard to understand whether the white spot in the middle is part of the texture of the plane or light source.

Maybe adding an object in the scene will help?

**Comment by Speierers** [comment]
Much better! I would remove the stand and just keep the sphere. Also maybe tilt the light a bit so things arre not too symmetrical.

I am also wondering whether we could find a "better looking" texture?

I just realized that you only pushed the image files here. Could you please add the scene to the `/resources/data/docs/scenes/` folder (there is a sphere in `/resources/data/docs/scenes/meshes`) and simply generate the images with the python script? (`render_documnetation_images.py`)
This way we will be able to easily re-generate the doc images if necessary 😉

**Comment by mehrab2603** [comment]
Added the scene files. I don't have any nice textures and so just linked against `pattern.jpg` in the texture folder.

**Comment by Speierers** [comment]
Great! Almost there 😉 

The spot light is really bright, there is almost no constrast on those images unfortunately. Could we dim the light a little bit?

Could even have multiple spot light with different angle and colors, that would look great! If it isn't too much to ask ^^ We really would like the documentation images to look nice!

**Comment by mehrab2603** [comment]
Can't dim the spot light much more than what it is because the envmap is too bright and dimming makes the spot light almost fade away. Replacing the envmap with a low intensity constant emitter and making the spot lights a little dimmer (can dim more if needed), I get this.

emitter_spot _no_pattern

Is this acceptable?

**Comment by Speierers** [comment]
Perfect! Just make sure the images is converged before pushing!
Could we do the same with textured spot light?
Thanks a lot @mehrab2603

**Comment by mehrab2603** [comment]
Could you please explain what you mean by converged? And by "same" do you mean to replace the envmap with a constant emitter the same way? Is the texture itself acceptable?

emitter_spot_pattern

**Comment by Speierers** [comment]
Yes this one with the texture looks good too me!

By more converged I mean rendering with a higher number of sample per pixel to reduce the noise in the image.

The `render_documentation_images.py` takes a `--spp` argument to specify the number of samples per pixel. You could try something like 1024 or higher.

**Comment by mehrab2603** [comment]
Alright. Should I remove the 2 images I pushed in the `resources/data/docs/emitter` directory and just link against the files in the `resources/data/docs/render` folder in the spot light doc?

**Comment by mehrab2603** [comment]
Done.

**Comment by Speierers** [comment]
Amazing!

**Pull request merged**
